### ISSUE TITLE
setup.py fails on installing via git+https in a virtualenv

### ISSUE THREAD

**Issue by gretel** [paperhive/ansible-ec2-inventory#4]
in `requirements.txt`:

```
-e git+https://github.com/paperhive/ansible-ec2-inventory.git#egg=ansible-ec2-inventory
ansible-ec2-inventory
```

```
$ pip install -U -r requirements.txt
...
  Updating /Users/tom/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/src/ansible-ec2-inventory clone
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/tom/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/src/ansible-ec2-inventory/setup.py", line 25, in <module>
        long_description=read('README'),
      File "/Users/tom/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/src/ansible-ec2-inventory/setup.py", line 15, in read
        encoding='utf-8'
      File "/Users/tom/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/Users/tom/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/src/ansible-ec2-inventory/README'
```

**Comment by andrenarchy** [comment]
I suggest to install the module via PyPi: `pip install ansible-ec2-inventory`.

Feel free to reopen if this is not an option for you.
